
CREATE DATABASE VehicleImpoundmentDB;
USE VehicleImpoundmentDB;

-- Table: IMPOUNDMENTFACILITY_STAT
CREATE TABLE IMPOUNDMENTFACILITY_STAT (
    CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(40)
);

-- Table: LMBAYSTAT
CREATE TABLE LMBAYSTAT (
    CODE CHAR(2) PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

-- Table: LMBAYACT
CREATE TABLE LMBAYACT (
    CODE CHAR(2) PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

-- Table: BAY
CREATE TABLE BAY (
    BAYID INT PRIMARY KEY,
    BAYNUMBER INT,
    BAYSTAT CHAR(2),
    BAYACTCODE CHAR(2),
    IMPOUNDMENT_FACILITYID INT,
    FOREIGN KEY (BAYSTAT) REFERENCES LMBAYSTAT(CODE),
    FOREIGN KEY (BAYACTCODE) REFERENCES LMBAYACT(CODE),
    FOREIGN KEY (IMPOUNDMENT_FACILITYID) REFERENCES IMPOUNDMENT_FACILITY(FACILITYID)
);

-- Table: PROVINCE
CREATE TABLE PROVINCE (
    PROVCID CHAR(1) PRIMARY KEY,
    ENGLISHPROV VARCHAR(20),
    PROVECGTMARK CHAR(2)
);

-- Table: MUNICIPALITY
CREATE TABLE MUNICIPALITY (
    MUNICIPALID INT PRIMARY KEY,
    PROVINCEPROVCID CHAR(1),
    MUNICIPALCODE VARCHAR(10),
    LMMUNICCODE VARCHAR(2),
    FOREIGN KEY (PROVINCEPROVCID) REFERENCES PROVINCE(PROVCID)
);

-- Table: LMMUNIC
CREATE TABLE LMMUNIC (
    CODE VARCHAR(2) PRIMARY KEY,
    DESCRIPTION VARCHAR(30)
);

-- Table: FACILITY
CREATE TABLE IMPOUNDMENT_FACILITY (
    FACILITYID INT PRIMARY KEY,
    POUNDNAME VARCHAR(30),
    DATE_FROM DATE,
    DATE_TO DATE,
    MAXWEIGHT INT,
    NUMBEROFBAYS INT,
    STREETADDRESS1 VARCHAR(30),
    STREETADDRESS2 VARCHAR(30),
    STREETADDRESS3 VARCHAR(30),
    STREETADDRESS4 VARCHAR(30),
    STREETPOSTCD VARCHAR(10),
    LATITUDE VARCHAR(20),
    LONGITUDE VARCHAR(20),
    CELLPHONE VARCHAR(15),
    EMAILADDR VARCHAR(50),
    MUNICIPALITYMUNICIPALID INT,
    PROVINCEPROVCID CHAR(1),
    IMPOUNDMENTFACILITY_STATCODE INT,
    FOREIGN KEY (MUNICIPALITYMUNICIPALID) REFERENCES MUNICIPALITY(MUNICIPALID),
    FOREIGN KEY (PROVINCEPROVCID) REFERENCES PROVINCE(PROVCID),
    FOREIGN KEY (IMPOUNDMENTFACILITY_STATCODE) REFERENCES IMPOUNDMENTFACILITY_STAT(CODE)
);

-- Table: MVDRIVER
CREATE TABLE MVDRIVER (
    DRIVERID INT PRIMARY KEY,
    SourceDocType CHAR(2),
    IDNumber INT,
    CELLPHONE VARCHAR(15),
    NAME VARCHAR(35),
    SURNAME VARCHAR(35),
    STREETADDR1 VARCHAR(30),
    STREETADDR2 VARCHAR(30),
    STREETADDR3 VARCHAR(30),
    STREETADDR4 VARCHAR(30),
    EMAILADDR VARCHAR(50),
    SIGNATURE BLOB,
    DRIVERPRESENT CHAR(2)
);

-- Table: IMPOUNDED_MV
CREATE TABLE IMPOUNDED_MV (
    IMPOUNDMENTNUMBER VARCHAR(255) PRIMARY KEY,
    SEQNO INT,
    IMPOUNDMENTLOCATION INT,
    IMPOUND_DATE DATE,
    BOOKED_DATE DATE,
    RELEASE_DATE DATE,
    OFFICERRE_NUMBER INT,
    MVSTATCODE INT,
    BAYID INT,
    FACILITYID INT,
    IMPOUNDMENT_REASON INT,
    VEHICLEID INT,
    MVDRIVERDRIVERID INT,
    TRAFFICOFFICEROFFICERID INT,
    TOWAGENTID INT,
    VEHICLE_CONDITIONCONDITIONID INT,
    REMARKS VARCHAR(255),
    FOREIGN KEY (MVSTATCODE) REFERENCES LMIMPOUNDED_MVSTAT(CODE),
    FOREIGN KEY (FACILITYID) REFERENCES IMPOUNDMENT_FACILITY(FACILITYID),
    FOREIGN KEY (IMPOUNDMENT_REASON) REFERENCES LMIMPOUNDMENT_REASON(CODE),
    FOREIGN KEY (VEHICLEID) REFERENCES VEHICLE(VEHICLEID),
    FOREIGN KEY (MVDRIVERDRIVERID) REFERENCES MVDRIVER(DRIVERID),
    FOREIGN KEY (TRAFFICOFFICEROFFICERID) REFERENCES TRAFFICOFFICER(OFFICERID),
    FOREIGN KEY (TOWAGENTID) REFERENCES TOW_AGENT(TOWAGENT_ID),
    FOREIGN KEY (VEHICLE_CONDITIONCONDITIONID) REFERENCES VEHICLE_CONDITION(CONDITIONID)
);

-- Table: LMIMPOUNDED_MVSTAT
CREATE TABLE LMIMPOUNDED_MVSTAT (
    CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(40)
);

-- Table: LMIMPOUNDMENT_REASON
CREATE TABLE LMIMPOUNDMENT_REASON (
    CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

-- Table: TOW_AGENT
CREATE TABLE TOW_AGENT (
    TOWAGENT_ID INT PRIMARY KEY,
    SourceDocType CHAR(2),
    IDNumber INT,
    NAME VARCHAR(25),
    STREETADDRESS1 VARCHAR(30),
    STREETADDRESS2 VARCHAR(30),
    STREETADDRESS3 VARCHAR(30),
    STREETADDRESS4 VARCHAR(30),
    STREETPOSTCD VARCHAR(10),
    CELLPHONE VARCHAR(15),
    EMAILADDR VARCHAR(50),
    MUNICIPALITYMUNICIPALID INT,
    FOREIGN KEY (MUNICIPALITYMUNICIPALID) REFERENCES MUNICIPALITY(MUNICIPALID)
);

-- Table: TOWAGENT_VEHICLE
CREATE TABLE TOWAGENT_VEHICLE (
    TOWHEADID INT PRIMARY KEY,
    TOW_AGHTOWAGENT_ID INT,
    VEHICLETYPE VARCHAR(30),
    VINNUMBER VARCHAR(17),
    FOREIGN KEY (TOW_AGHTOWAGENT_ID) REFERENCES TOW_AGENT(TOWAGENT_ID)
);

-- Table: TOWAGENT_DRIVER
CREATE TABLE TOWAGENT_DRIVER (
    TOWDRIVERID INT PRIMARY KEY,
    SOURCEDOCTYPE CHAR(2),
    IDNumber INT,
    NAME VARCHAR(25),
    SURNAME VARCHAR(25),
    TOW_AGHTOWAGENT_ID INT,
    SIGNATURE BLOB,
    FOREIGN KEY (TOW_AGHTOWAGENT_ID) REFERENCES TOW_AGENT(TOWAGENT_ID)
);

-- Table: TRAFFICOFFICER
CREATE TABLE TRAFFICOFFICER (
    OFFICERID INT PRIMARY KEY,
    SOURCEDOCTYPE CHAR(2),
    IDNUMBER INT,
    NAME VARCHAR(25),
    SURNAME VARCHAR(25),
    CELLPHONE VARCHAR(15),
    EMAILADDR VARCHAR(50),
    OFFICER_NUMBER INT,
    MUNICIPALITYMUNICIPALID INT,
    SIGNATURE BLOB,
    FOREIGN KEY (MUNICIPALITYMUNICIPALID) REFERENCES MUNICIPALITY(MUNICIPALID)
);

-- Table: VEHICLE
CREATE TABLE VEHICLE (
    VEHICLEID INT PRIMARY KEY,
    VEHICLEPLATE VARCHAR(30),
    VINNUMBER VARCHAR(30),
    MAKE VARCHAR(30),
    MODEL VARCHAR(30),
    WHEELBASE VARCHAR(30),
    LICENCEEXP DATE,
    ROADWARRANTYEXP DATE,
    VEHICLETYPE VARCHAR(30),
    VEHICLECATEGORY VARCHAR(30),
    VEHICLEMAKE VARCHAR(30),
    VEHICLEBODYMARK VARCHAR(30),
    VEHICLEMODEL VARCHAR(30),
    VEHICLETYPE2 VARCHAR(30),
    ODOMETERREADING INT
);

-- Table: VEHICLE_CONDITION
CREATE TABLE VEHICLE_CONDITION (
    CONDITIONID INT PRIMARY KEY,
    DOORUNLOCKED CHAR(2),
    TRUNKUNLOCKED CHAR(2),
    KEYS_MISSING CHAR(2),
    COMMENTS VARCHAR(255)
);

-- Table: VEHICLE_INVENTORY
CREATE TABLE VEHICLE_INVENTORY (
    INVENTORY_ID INT PRIMARY KEY,
    ENGINE CHAR(2),
    BATTERY CHAR(2),
    MIRRORS CHAR(2),
    JACK CHAR(2),
    WHEEL CHAR(2),
    RADIO CHAR(2),
    TAPEDECK CHAR(2),
    RIMWHEEL CHAR(2),
    RRWHEEL CHAR(2),
    IRWHEEL CHAR(2),
    WHEELCOVERS CHAR(2),
    CBRADIO CHAR(2),
    OTHER CHAR(2),
    IMPOUNDED_MVIMPOUNDMENTNUMBER VARCHAR(255),
    FOREIGN KEY (IMPOUNDED_MVIMPOUNDMENTNUMBER) REFERENCES IMPOUNDED_MV(IMPOUNDMENTNUMBER)
);

-- Table: MV_INSPECTION
CREATE TABLE MV_INSPECTION (
    INSPECTION_ID INT PRIMARY KEY,
    LPICTURE BLOB,
    PICTURE1 BLOB,
    PICTURE2 BLOB,
    PICTURE3 BLOB,
    IMPOUNDED_MVIMPOUNDMENTNUMBER VARCHAR(255),
    FOREIGN KEY (IMPOUNDED_MVIMPOUNDMENTNUMBER) REFERENCES IMPOUNDED_MV(IMPOUNDMENTNUMBER)
);
